### ISSUE TITLE
Use Go Test Timeout to set Knuu Timeout

### ISSUE THREAD

**Issue by tty47** [celestiaorg/knuu#267]
hello!

It would be great to set the `KNUU_TIMEOUT` value from `go test -timeout`, this will help us to specify the timeout value and don't face issues like:

Set the env var:
```bash
export KNUU_TIMEOUT=25m
``` 

And then:
``` go
panic: test timed out after 10m0s
running tests:
        TestFolderCached (10m0s)
``` 

cheers! 🚀 
```[tasklist]
### Tasks
- [ ] `KNUU_TIMEOUT` -> from `go test -timeout`
- [ ] if we set `KNUU_TIMEOUT` will override `go test -timeout`
- [ ] `go test -timeout` has priority over `KNUU_TIMEOUT`
```

**Comment by k124k3n** [comment]
So,`KNUU_TIMEOUT` can only set up from `go test -timeout`?

**Comment by k124k3n** [comment]
did point 2 and 3 contradict each other?

**Comment by smuu** [comment]
not tested
