### ISSUE TITLE
feat: load `.env` and generate a JSON file in a tmp path

### ISSUE THREAD

**Issue by tty47** [celestiaorg/knuu#301]
implement load the .env in the Initialization phase to generate a JSON file with the values in a tmp path.

check:
- https://github.com/joho/godotenv

this will replace: https://github.com/celestiaorg/knuu/issues/289

instead of using the secrets, add the feature to knuu to be able to read from a .env file, where you can place the credentials
during the init process in knuu, it reads the vile and writes the values to a tmp JSON file (path and name that you specify), and then, the instance will have it available:

```[tasklist]
### Tasks
- [x] Use .env file to store the S3 bucket creds
- [x] During the initialization, read from the env and write to a tmp JSON file
- [x] Mount that file to the Instance
```
