### ISSUE TITLE
[EPIC] Knuu enhancements

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#486]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/knuu/issues/482
- [ ] https://github.com/celestiaorg/knuu/issues/473
- [ ] https://github.com/celestiaorg/knuu/issues/433
- [ ] https://github.com/celestiaorg/knuu/issues/405
- [ ] https://github.com/celestiaorg/knuu/issues/390
- [ ] https://github.com/celestiaorg/knuu/issues/388
- [ ] https://github.com/celestiaorg/knuu/issues/367
- [ ] https://github.com/celestiaorg/knuu/issues/319
- [ ] https://github.com/celestiaorg/knuu/issues/317
- [ ] https://github.com/celestiaorg/knuu/issues/316
- [ ] https://github.com/celestiaorg/knuu/issues/312
- [ ] https://github.com/celestiaorg/knuu/issues/306
- [ ] https://github.com/celestiaorg/knuu/issues/292
- [ ] https://github.com/celestiaorg/knuu/issues/287
- [ ] https://github.com/celestiaorg/knuu/issues/225
- [ ] https://github.com/celestiaorg/knuu/issues/192
- [ ] https://github.com/celestiaorg/knuu/issues/167
- [ ] https://github.com/celestiaorg/knuu/issues/131
- [ ] https://github.com/celestiaorg/knuu/issues/103
- [ ] https://github.com/celestiaorg/knuu/issues/98
- [ ] https://github.com/celestiaorg/knuu/issues/96
- [ ] https://github.com/celestiaorg/knuu/issues/95
- [ ] https://github.com/celestiaorg/knuu/issues/90
- [ ] https://github.com/celestiaorg/knuu/issues/74
- [ ] https://github.com/celestiaorg/knuu/issues/51
- [ ] https://github.com/celestiaorg/knuu/issues/38
- [ ] https://github.com/celestiaorg/knuu/issues/30
- [ ] https://github.com/celestiaorg/knuu/issues/15
```
