### ISSUE TITLE
[EPIC] Knuu bugs

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#487]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/knuu/issues/485
- [ ] https://github.com/celestiaorg/knuu/issues/464
- [ ] https://github.com/celestiaorg/knuu/issues/463
- [ ] https://github.com/celestiaorg/knuu/issues/420
- [ ] https://github.com/celestiaorg/knuu/issues/367
- [ ] https://github.com/celestiaorg/knuu/issues/320
- [ ] https://github.com/celestiaorg/knuu/issues/225
- [ ] https://github.com/celestiaorg/knuu/issues/208
- [ ] https://github.com/celestiaorg/knuu/issues/202
- [ ] https://github.com/celestiaorg/knuu/issues/109
- [ ] https://github.com/celestiaorg/knuu/issues/98
- [ ] https://github.com/celestiaorg/knuu/issues/83
- [ ] https://github.com/celestiaorg/knuu/issues/51
- [ ] https://github.com/celestiaorg/knuu/issues/34
```
