### ISSUE TITLE
[EPIC] Knuu refactoring

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#488]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/knuu/issues/467
- [ ] https://github.com/celestiaorg/knuu/issues/462
- [ ] https://github.com/celestiaorg/knuu/issues/458
- [ ] https://github.com/celestiaorg/knuu/issues/457
- [ ] https://github.com/celestiaorg/knuu/issues/456
- [ ] https://github.com/celestiaorg/knuu/issues/386
- [ ] https://github.com/celestiaorg/knuu/issues/130
- [ ] https://github.com/celestiaorg/knuu/issues/123
- [ ] https://github.com/celestiaorg/knuu/issues/116
- [ ] https://github.com/celestiaorg/knuu/issues/103
- [ ] https://github.com/celestiaorg/knuu/issues/15
```
