### ISSUE TITLE
[EPIC] Knuu documentation

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#489]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/knuu/issues/480
- [ ] https://github.com/celestiaorg/knuu/issues/474
- [ ] https://github.com/celestiaorg/knuu/issues/394
- [ ] https://github.com/celestiaorg/knuu/issues/259
- [ ] https://github.com/celestiaorg/knuu/issues/134
- [ ] https://github.com/celestiaorg/knuu/issues/100
- [ ] https://github.com/celestiaorg/knuu/issues/96
- [ ] https://github.com/celestiaorg/knuu/issues/95
- [ ] https://github.com/celestiaorg/knuu/issues/29
```
