### ISSUE TITLE
[EPIC] Knuu release v0.15.0

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#495]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/knuu/issues/123
- [ ] https://github.com/celestiaorg/knuu/issues/38
- [ ] https://github.com/celestiaorg/knuu/issues/484
- [ ] https://github.com/celestiaorg/knuu/issues/511
- [ ] https://github.com/celestiaorg/knuu/issues/386
- [ ] https://github.com/celestiaorg/knuu/issues/431
```

**Comment by smuu** [comment]
Migrated to milestone: https://github.com/celestiaorg/knuu/milestone/1
