### ISSUE TITLE
[EPIC] Knuu release v0.16.0

### ISSUE THREAD

**Issue by smuu** [celestiaorg/knuu#499]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/knuu/issues/512
- [ ] https://github.com/celestiaorg/knuu/issues/479
- [ ] https://github.com/celestiaorg/knuu/issues/319
- [ ] https://github.com/celestiaorg/knuu/issues/467
- [ ] https://github.com/celestiaorg/knuu/issues/15
- [ ] https://github.com/celestiaorg/knuu/issues/420
- [ ] https://github.com/celestiaorg/knuu/issues/501
- [ ] https://github.com/celestiaorg/knuu/issues/485
```

**Comment by smuu** [comment]
Migrated to milestone: https://github.com/celestiaorg/knuu/milestone/2
